name: CI
on:
  push:
    paths-ignore:
      - '**.md'
      - 'examples/*'
      - 'docs/*'
jobs:
  test:
    name: Run checks and tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - '26.1'
          - '26.2'
          - '26.3'
          - snapshot
    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - uses: actions/checkout@v2
      - name: Setup checks
        run: 'make setup-check'
      - name: Run checks
        run: 'make check'
      - name: Setup unit testing
        run: 'make setup-tests'
      - name: Run ERT unit tests
        run: 'make test'
